selected_tournament: "world_cup"

tournaments:
  world_cup:
    raw_path: "data/raw/matches_1930_2022.csv"
    processed_path: "data/processed/cleaned_wm_data.csv"
    live_path: "data/raw/wm2026_live.csv"
    predictions_path: "data/processed/predictions.csv"
    history_path: "data/processed/prediction_history.csv"

model:
  decay_rate: 0.15

prediction:
  prediction_window_days: 3